export const DONE: string[] = [
  "Dashboard visuell finalisiert",
  "Objekte-Liste visuell (Typ-Spalte, Hausverwaltung, Farben)",
  "Objekt-Detailseite visuell",
  "Imports-Seite visuell (Quellauswahl, History-Tabelle)",
  "Dokumente-Seite visuell (echte Datentabelle)",
  "Opportunities-Seite visuell (FG Finanz)",
  "Incentives / Support / Settings visuell",
  "Kundenportal alle Seiten (Übersicht, Dokumente, Nachrichten, Einstellungen)",
  "Portal-Dashboard mit echten Kundendaten",
  "Test-Kunde angelegt (kunde@test.de)",
  "middleware.ts Konflikt behoben",
  "allowedDevOrigins konfiguriert",
  "Objekte-Liste überarbeitet (Spalten, WEG/Privat, Malo, Zählernummer, KNR)",
  "Objekt-Detailseite überarbeitet (Stammdaten kompakt, Aktuelle Daten Box, KdNr Zuordnung)",
  "Teleson-Tabelle in Notion-Reihenfolge gebracht",
  "Dashboard Objekttabelle aktualisiert",
  "Kategorien aus UI entfernt",
  "Hausverwaltung global umbenannt",
  "Portal-Org-Zuordnung + RLS (Migrations 023 + 024)",
  "Portal-Dashboard mit echten KPIs (Objekte, Strom, Gas, FG Finanz, Potenziale)",
  "Portal-Objekte-Seite mit Detailansicht",
  "Portal-Ansprechpartner-Seite (zwei Spalten FG Finanz / Teleson)",
  "Portal-FG Finanz Placeholder-Seite",
  "Portal-Incentives Placeholder-Seite",
  "Schnell-Upload-Widget in Sidebar",
  "Kunden-Login produktiv (Test-Kunde mit Org verknüpft)",
  "Hausverwaltung Pfafflinger angelegt + alle Objekte zugeordnet",
  "UHID System eingebaut (HV-XXXXX / OBJ-XXXXX, automatisch via DB-Trigger)",
  "Hausverwaltungs-Auswahl beim Import (Notion + Datei)",
  "Kunden-Account automatisch bei neuer Hausverwaltung anlegen",
  "Credentials-Banner mit Copy-Buttons",
  "Fuzzy-Match Logik für Hausverwaltungs-Namen",
  "Adress-Mapping beim Import (WEG → Straße/Stadt/PLZ)",
  "Duplikat-Schutz beim Import (Strom+Gas → 1 Objekt)",
  "Objektname global nur Straße (Admin + Portal)",
  "Full Flow Test erfolgreich (Import → Portal → Login)",
  "sync.ts organization_id Fix",
  "Forced Password Change beim ersten Kunden-Login",
  "Dokument-Zuordnung im Admin (Upload → Objekt zuweisen)",
  "Playwright automatisches Testing Setup",
  "Kundenportal: Teleson-Daten anzeigen (Entscheidung Miguel)",
  "Mitarbeiter-Login produktiv",
  "Dashboard echte Datenlogik",
  "Dokumente 3-Stufen-Logik (Eingang → HV Allgemein → Objekt-spezifisch)",
  "Nav-Badge für unbearbeitete Dokumente im Eingang",
  "Ansprechpartner WhatsApp-Links mit vorausgefülltem Text",
  "Hausverwaltungs-Dokumente Upload-Logik (Hauptordner)",
  "Card-Metadaten angereichert (Dashboard-Aging-Counter + Roadmap-Übersicht)",
]

export const OPEN: string[] = [
  "Benutzerverwaltung in Einstellungen (Nutzer, Sperren, Passwort-Reset)",
  "Sequences zurücksetzen nach Cleanup (HV/OBJ ab 00001)",
  "UI-Polish / Full Visual Audit (professioneller, hochwertiger)",
  "FG Finanz Import-Route (/api/import/fg-finanz)",
  "Match-Review-Queue UI bauen",
  "Website / Außenauftritt (utility-hub.one)",
  "Kontakte-Seite + Tabelle (migration + UI)",
]

export const FUTURE: string[] = [
  "Upsell-Erkennung basierend auf Daten (regelbasiert)",
  "Notion ↔ Supabase Auto-Sync",
  "Wochen-/Monatsreports automatisch",
  "Incentives-Logik klären und einbauen",
  "Kunden-Login Logik festlegen",
  "Mitarbeiter-Login Logik festlegen",
  "Admin-Einstellungen: Rechteverwaltung pro Account",
  "System Health Tracking (Performance, Sicherheit)",
  "Landingpage vollständig ausbauen",
  "Drag & Drop Logiken ausbauen",
]
